apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: builds.registry.svc.cluster.local/yolean/kafka-keyvalue-nodejs-itest
    context: .
    custom:
      buildCommand: y-build --opt filename=itest.Dockerfile
      dependencies:
        dockerfile:
          path: ./itest.Dockerfile
    # sync:
    #   manual:
    #   - src: src/**
    #     dest: src
deploy:
  kustomize:
    path: ./variant-dev
